name = "unify-instructions"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]

# For Cloudflare Pages deployment
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "unify-comments"
database_id = "1dda6ae2-ff9d-41d8-8c11-be512e701b85"